# Example config for a DU with one 20MHz TDD cell using a USRP as RF frontend.
f1ap:
  cu_cp_addr: 127.0.0.88
  bind_addr: 127.0.0.87

ru_sdr:
  device_driver: uhd
  device_args: type=b200
  srate: 23.04
  otw_format: sc12
  clock: gpsdo  
  tx_gain: 75
  rx_gain: 40

cell_cfg:
  dl_arfcn: 368500
  band: 3
  channel_bandwidth_MHz: 20
  common_scs: 15
  plmn: "00101"
  tac: 77
  pci: 99
  pdcch:
    dedicated:
      ss2_type: common                                            # Set search space to common to match capabilities
      dci_format_0_1_and_1_1: false                               # Use fallback DCI to match srsUE capabilities
    common:
      ss0_index: 0
      coreset0_index: 12
  prach:
    prach_config_index: 1   

log:
  filename: /tmp/du.log
  all_level: debug

pcap:
  mac_enable: true
  mac_filename: /tmp/du_mac.pcap
  f1ap_enable: true
  f1ap_filename: /tmp/du_f1ap.pcap
  f1u_enable: true
  f1u_filename: /tmp/du_f1u.pcap
  rlc_enable: true
  rlc_rb_type: all
  rlc_filename: /tmp/du_rlc.pcap
